# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8692ec419304465e4b6016b002ed8694828783a2af941e35ccc32a8fe8fc2d39e49f2388ebe63c2bfe73f9a46c3e98d1f1077ebc212e87aa5f8f744ccf9bff1
  consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>

test:
  secret_key_base: bd105c3e369bfc267cc811c4c0193ca8991c9e46785ca940f74b1a0783f85d235a0fd28a1c6f1692b8f5e64fb01d7b425b43cec01c70caf04a4b450430c7006e
  consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  test_account:
    uid: <%= ENV["TWITTER_TEST_ID"] %>
    username: <%= ENV["TWITTER_TEST_USERNAME"] %>
    token: <%= ENV["TWITTER_TEST_TOKEN"] %>
    secret: <%= ENV["TWITTER_TEST_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
